-- MySQL Script generated by MySQL Workbench
-- Fri May 16 21:25:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinical
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinical` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema users
-- -----------------------------------------------------
-- This schema was created for a stub table

-- -----------------------------------------------------
-- Schema users
--
-- This schema was created for a stub table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users` ;
USE `clinical` ;

-- -----------------------------------------------------
-- Table `clinical`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinical`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `role` ENUM('doctor', 'patient') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinical`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinical`.`patients` (
  `patients_id` INT NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` ENUM('male', 'female', 'other') NOT NULL,
  PRIMARY KEY (`patients_id`),
  CONSTRAINT `patient_id`
    FOREIGN KEY (`patients_id`)
    REFERENCES `clinical`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinical`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinical`.`doctors` (
  `doctors_id` INT NOT NULL,
  `specialisation` VARCHAR(100) NOT NULL,
  `license_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`doctors_id`),
  UNIQUE INDEX `license_number_UNIQUE` (`license_number` ASC) VISIBLE,
  CONSTRAINT `doctor_id`
    FOREIGN KEY (`doctors_id`)
    REFERENCES `clinical`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinical`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinical`.`appointments` (
  `appointments_id` INT NOT NULL AUTO_INCREMENT,
  `patients_id` INT NULL,
  `doctor_id` INT NULL,
  `appointment_date` DATETIME NOT NULL,
  `status` ENUM('scheduled', 'completed', 'cancelled') NULL DEFAULT 'scheduled',
  `notes` TEXT NULL,
  PRIMARY KEY (`appointments_id`),
  INDEX `appointments.doctor_id_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `appointments.patient_id_idx` (`patients_id` ASC) VISIBLE,
  CONSTRAINT `appointments.patient_id`
    FOREIGN KEY (`patients_id`)
    REFERENCES `clinical`.`patients` (`patients_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appointments.doctor_id`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `clinical`.`doctors` (`doctors_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `users` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
